spring.application.name=transport-management
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.config.import=optional:classpath:.env
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.enabled=true
server.compression.enabled=false
server.http2.enabled=false
twilio.account_sid=${TWILIO_SID}
twilio.auth_token=${TWILIO_TOKEN}
twilio.phone_number=${TWILIO_NUMBER}
logging.level.root=INFO
